# Generated by Django 5.1.7 on 2025-03-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irrigation', models.BooleanField(default=False)),
                ('climate_control', models.CharField(choices=[('heat', 'Heat'), ('cool', 'Cool'), ('off', 'Off')], default='off', max_length=10)),
                ('nutrient_delivery', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
