# Generated by Django 5.1.7 on 2025-03-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalcontent',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
