# Generated by Django 5.1.7 on 2025-03-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_educationalcontent_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalcontent',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
